#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative 'lib/setup'

user = Interface.new
options = if user.defaults?
            {}
          else
            { max_bets: user.max_bets,
              max_size: user.max_size,
              irregular: !user.irregular }
          end
drill = Drill.new(options)

loop do
  drill.new_problem
  drill.display
  until drill.evaluate(user.answer) do user.red('Try again...') end
end
